# Generated by Django 5.0.4 on 2024-06-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booknotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
